// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: service.proto

package hivemindv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PlanStep struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         int32                  `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Action        string                 `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlanStep) Reset() {
	*x = PlanStep{}
	mi := &file_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlanStep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlanStep) ProtoMessage() {}

func (x *PlanStep) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlanStep.ProtoReflect.Descriptor instead.
func (*PlanStep) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{0}
}

func (x *PlanStep) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *PlanStep) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *PlanStep) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type Plan struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Steps         []*PlanStep            `protobuf:"bytes,1,rep,name=steps,proto3" json:"steps,omitempty"`
	CurrentIndex  int32                  `protobuf:"varint,2,opt,name=current_index,json=currentIndex,proto3" json:"current_index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Plan) Reset() {
	*x = Plan{}
	mi := &file_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Plan) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Plan) ProtoMessage() {}

func (x *Plan) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Plan.ProtoReflect.Descriptor instead.
func (*Plan) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{1}
}

func (x *Plan) GetSteps() []*PlanStep {
	if x != nil {
		return x.Steps
	}
	return nil
}

func (x *Plan) GetCurrentIndex() int32 {
	if x != nil {
		return x.CurrentIndex
	}
	return 0
}

type StartSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	WorkflowId    string                 `protobuf:"bytes,2,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	Task          string                 `protobuf:"bytes,3,opt,name=task,proto3" json:"task,omitempty"`
	Plan          *Plan                  `protobuf:"bytes,4,opt,name=plan,proto3" json:"plan,omitempty"`
	HivemindId    string                 `protobuf:"bytes,5,opt,name=hivemind_id,json=hivemindId,proto3" json:"hivemind_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartSessionRequest) Reset() {
	*x = StartSessionRequest{}
	mi := &file_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartSessionRequest) ProtoMessage() {}

func (x *StartSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartSessionRequest.ProtoReflect.Descriptor instead.
func (*StartSessionRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{2}
}

func (x *StartSessionRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *StartSessionRequest) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

func (x *StartSessionRequest) GetTask() string {
	if x != nil {
		return x.Task
	}
	return ""
}

func (x *StartSessionRequest) GetPlan() *Plan {
	if x != nil {
		return x.Plan
	}
	return nil
}

func (x *StartSessionRequest) GetHivemindId() string {
	if x != nil {
		return x.HivemindId
	}
	return ""
}

type StartSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	HivemindId    string                 `protobuf:"bytes,2,opt,name=hivemind_id,json=hivemindId,proto3" json:"hivemind_id,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartSessionResponse) Reset() {
	*x = StartSessionResponse{}
	mi := &file_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartSessionResponse) ProtoMessage() {}

func (x *StartSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartSessionResponse.ProtoReflect.Descriptor instead.
func (*StartSessionResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{3}
}

func (x *StartSessionResponse) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *StartSessionResponse) GetHivemindId() string {
	if x != nil {
		return x.HivemindId
	}
	return ""
}

func (x *StartSessionResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *StartSessionResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type UpdateContextRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	Field         string                 `protobuf:"bytes,2,opt,name=field,proto3" json:"field,omitempty"`
	Data          *structpb.Struct       `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateContextRequest) Reset() {
	*x = UpdateContextRequest{}
	mi := &file_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateContextRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateContextRequest) ProtoMessage() {}

func (x *UpdateContextRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateContextRequest.ProtoReflect.Descriptor instead.
func (*UpdateContextRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateContextRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *UpdateContextRequest) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *UpdateContextRequest) GetData() *structpb.Struct {
	if x != nil {
		return x.Data
	}
	return nil
}

type UpdateContextResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateContextResponse) Reset() {
	*x = UpdateContextResponse{}
	mi := &file_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateContextResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateContextResponse) ProtoMessage() {}

func (x *UpdateContextResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateContextResponse.ProtoReflect.Descriptor instead.
func (*UpdateContextResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{5}
}

type GetContextWindowRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RunId          string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	AgentId        string                 `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	MaxTokens      int32                  `protobuf:"varint,3,opt,name=max_tokens,json=maxTokens,proto3" json:"max_tokens,omitempty"`
	ConversationId string                 `protobuf:"bytes,4,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	ContextMode    string                 `protobuf:"bytes,5,opt,name=context_mode,json=contextMode,proto3" json:"context_mode,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetContextWindowRequest) Reset() {
	*x = GetContextWindowRequest{}
	mi := &file_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetContextWindowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetContextWindowRequest) ProtoMessage() {}

func (x *GetContextWindowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetContextWindowRequest.ProtoReflect.Descriptor instead.
func (*GetContextWindowRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{6}
}

func (x *GetContextWindowRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *GetContextWindowRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *GetContextWindowRequest) GetMaxTokens() int32 {
	if x != nil {
		return x.MaxTokens
	}
	return 0
}

func (x *GetContextWindowRequest) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *GetContextWindowRequest) GetContextMode() string {
	if x != nil {
		return x.ContextMode
	}
	return ""
}

type GetContextWindowResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Context           string                 `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	ModeUsed          string                 `protobuf:"bytes,2,opt,name=mode_used,json=modeUsed,proto3" json:"mode_used,omitempty"`
	TurnNumber        int32                  `protobuf:"varint,3,opt,name=turn_number,json=turnNumber,proto3" json:"turn_number,omitempty"`
	TotalTokens       int32                  `protobuf:"varint,4,opt,name=total_tokens,json=totalTokens,proto3" json:"total_tokens,omitempty"`
	DeltaTokensSaved  int32                  `protobuf:"varint,5,opt,name=delta_tokens_saved,json=deltaTokensSaved,proto3" json:"delta_tokens_saved,omitempty"`
	FullContextTokens int32                  `protobuf:"varint,6,opt,name=full_context_tokens,json=fullContextTokens,proto3" json:"full_context_tokens,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetContextWindowResponse) Reset() {
	*x = GetContextWindowResponse{}
	mi := &file_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetContextWindowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetContextWindowResponse) ProtoMessage() {}

func (x *GetContextWindowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetContextWindowResponse.ProtoReflect.Descriptor instead.
func (*GetContextWindowResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{7}
}

func (x *GetContextWindowResponse) GetContext() string {
	if x != nil {
		return x.Context
	}
	return ""
}

func (x *GetContextWindowResponse) GetModeUsed() string {
	if x != nil {
		return x.ModeUsed
	}
	return ""
}

func (x *GetContextWindowResponse) GetTurnNumber() int32 {
	if x != nil {
		return x.TurnNumber
	}
	return 0
}

func (x *GetContextWindowResponse) GetTotalTokens() int32 {
	if x != nil {
		return x.TotalTokens
	}
	return 0
}

func (x *GetContextWindowResponse) GetDeltaTokensSaved() int32 {
	if x != nil {
		return x.DeltaTokensSaved
	}
	return 0
}

func (x *GetContextWindowResponse) GetFullContextTokens() int32 {
	if x != nil {
		return x.FullContextTokens
	}
	return 0
}

type EndSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EndSessionRequest) Reset() {
	*x = EndSessionRequest{}
	mi := &file_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndSessionRequest) ProtoMessage() {}

func (x *EndSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndSessionRequest.ProtoReflect.Descriptor instead.
func (*EndSessionRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{8}
}

func (x *EndSessionRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

type TokensSaved struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	DeltaContext   int64                  `protobuf:"varint,1,opt,name=delta_context,json=deltaContext,proto3" json:"delta_context,omitempty"`
	Compression    int64                  `protobuf:"varint,2,opt,name=compression,proto3" json:"compression,omitempty"`
	CrossExecution int64                  `protobuf:"varint,3,opt,name=cross_execution,json=crossExecution,proto3" json:"cross_execution,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TokensSaved) Reset() {
	*x = TokensSaved{}
	mi := &file_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokensSaved) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokensSaved) ProtoMessage() {}

func (x *TokensSaved) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokensSaved.ProtoReflect.Descriptor instead.
func (*TokensSaved) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{9}
}

func (x *TokensSaved) GetDeltaContext() int64 {
	if x != nil {
		return x.DeltaContext
	}
	return 0
}

func (x *TokensSaved) GetCompression() int64 {
	if x != nil {
		return x.Compression
	}
	return 0
}

func (x *TokensSaved) GetCrossExecution() int64 {
	if x != nil {
		return x.CrossExecution
	}
	return 0
}

type EndSessionResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	RunId            string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	Status           string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	EpisodeId        string                 `protobuf:"bytes,3,opt,name=episode_id,json=episodeId,proto3" json:"episode_id,omitempty"`
	RecordingStatus  string                 `protobuf:"bytes,4,opt,name=recording_status,json=recordingStatus,proto3" json:"recording_status,omitempty"`
	CompressionRatio float64                `protobuf:"fixed64,5,opt,name=compression_ratio,json=compressionRatio,proto3" json:"compression_ratio,omitempty"`
	TokensSaved      *TokensSaved           `protobuf:"bytes,6,opt,name=tokens_saved,json=tokensSaved,proto3" json:"tokens_saved,omitempty"`
	Warning          string                 `protobuf:"bytes,7,opt,name=warning,proto3" json:"warning,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *EndSessionResponse) Reset() {
	*x = EndSessionResponse{}
	mi := &file_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndSessionResponse) ProtoMessage() {}

func (x *EndSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndSessionResponse.ProtoReflect.Descriptor instead.
func (*EndSessionResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{10}
}

func (x *EndSessionResponse) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *EndSessionResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *EndSessionResponse) GetEpisodeId() string {
	if x != nil {
		return x.EpisodeId
	}
	return ""
}

func (x *EndSessionResponse) GetRecordingStatus() string {
	if x != nil {
		return x.RecordingStatus
	}
	return ""
}

func (x *EndSessionResponse) GetCompressionRatio() float64 {
	if x != nil {
		return x.CompressionRatio
	}
	return 0
}

func (x *EndSessionResponse) GetTokensSaved() *TokensSaved {
	if x != nil {
		return x.TokensSaved
	}
	return nil
}

func (x *EndSessionResponse) GetWarning() string {
	if x != nil {
		return x.Warning
	}
	return ""
}

type RetrieveRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Intent          string                 `protobuf:"bytes,1,opt,name=intent,proto3" json:"intent,omitempty"`
	TaskType        string                 `protobuf:"bytes,2,opt,name=task_type,json=taskType,proto3" json:"task_type,omitempty"`
	Constraints     []string               `protobuf:"bytes,3,rep,name=constraints,proto3" json:"constraints,omitempty"`
	MaxTokens       int32                  `protobuf:"varint,4,opt,name=max_tokens,json=maxTokens,proto3" json:"max_tokens,omitempty"`
	Depth           int32                  `protobuf:"varint,5,opt,name=depth,proto3" json:"depth,omitempty"`
	MinConfidence   float64                `protobuf:"fixed64,6,opt,name=min_confidence,json=minConfidence,proto3" json:"min_confidence,omitempty"`
	ScopeType       string                 `protobuf:"bytes,7,opt,name=scope_type,json=scopeType,proto3" json:"scope_type,omitempty"`
	ScopeId         string                 `protobuf:"bytes,8,opt,name=scope_id,json=scopeId,proto3" json:"scope_id,omitempty"`
	IncludeUnscoped bool                   `protobuf:"varint,9,opt,name=include_unscoped,json=includeUnscoped,proto3" json:"include_unscoped,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RetrieveRequest) Reset() {
	*x = RetrieveRequest{}
	mi := &file_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetrieveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetrieveRequest) ProtoMessage() {}

func (x *RetrieveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetrieveRequest.ProtoReflect.Descriptor instead.
func (*RetrieveRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{11}
}

func (x *RetrieveRequest) GetIntent() string {
	if x != nil {
		return x.Intent
	}
	return ""
}

func (x *RetrieveRequest) GetTaskType() string {
	if x != nil {
		return x.TaskType
	}
	return ""
}

func (x *RetrieveRequest) GetConstraints() []string {
	if x != nil {
		return x.Constraints
	}
	return nil
}

func (x *RetrieveRequest) GetMaxTokens() int32 {
	if x != nil {
		return x.MaxTokens
	}
	return 0
}

func (x *RetrieveRequest) GetDepth() int32 {
	if x != nil {
		return x.Depth
	}
	return 0
}

func (x *RetrieveRequest) GetMinConfidence() float64 {
	if x != nil {
		return x.MinConfidence
	}
	return 0
}

func (x *RetrieveRequest) GetScopeType() string {
	if x != nil {
		return x.ScopeType
	}
	return ""
}

func (x *RetrieveRequest) GetScopeId() string {
	if x != nil {
		return x.ScopeId
	}
	return ""
}

func (x *RetrieveRequest) GetIncludeUnscoped() bool {
	if x != nil {
		return x.IncludeUnscoped
	}
	return false
}

type RetrieveResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	ContextText         string                 `protobuf:"bytes,1,opt,name=context_text,json=contextText,proto3" json:"context_text,omitempty"`
	ContextTokens       int32                  `protobuf:"varint,2,opt,name=context_tokens,json=contextTokens,proto3" json:"context_tokens,omitempty"`
	BudgetUsed          float64                `protobuf:"fixed64,3,opt,name=budget_used,json=budgetUsed,proto3" json:"budget_used,omitempty"`
	SkillsCount         int32                  `protobuf:"varint,4,opt,name=skills_count,json=skillsCount,proto3" json:"skills_count,omitempty"`
	PatternsCount       int32                  `protobuf:"varint,5,opt,name=patterns_count,json=patternsCount,proto3" json:"patterns_count,omitempty"`
	EpisodesCount       int32                  `protobuf:"varint,6,opt,name=episodes_count,json=episodesCount,proto3" json:"episodes_count,omitempty"`
	RetrievalLatencyMs  float64                `protobuf:"fixed64,7,opt,name=retrieval_latency_ms,json=retrievalLatencyMs,proto3" json:"retrieval_latency_ms,omitempty"`
	TokensSavedEstimate int64                  `protobuf:"varint,8,opt,name=tokens_saved_estimate,json=tokensSavedEstimate,proto3" json:"tokens_saved_estimate,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *RetrieveResponse) Reset() {
	*x = RetrieveResponse{}
	mi := &file_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetrieveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetrieveResponse) ProtoMessage() {}

func (x *RetrieveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetrieveResponse.ProtoReflect.Descriptor instead.
func (*RetrieveResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{12}
}

func (x *RetrieveResponse) GetContextText() string {
	if x != nil {
		return x.ContextText
	}
	return ""
}

func (x *RetrieveResponse) GetContextTokens() int32 {
	if x != nil {
		return x.ContextTokens
	}
	return 0
}

func (x *RetrieveResponse) GetBudgetUsed() float64 {
	if x != nil {
		return x.BudgetUsed
	}
	return 0
}

func (x *RetrieveResponse) GetSkillsCount() int32 {
	if x != nil {
		return x.SkillsCount
	}
	return 0
}

func (x *RetrieveResponse) GetPatternsCount() int32 {
	if x != nil {
		return x.PatternsCount
	}
	return 0
}

func (x *RetrieveResponse) GetEpisodesCount() int32 {
	if x != nil {
		return x.EpisodesCount
	}
	return 0
}

func (x *RetrieveResponse) GetRetrievalLatencyMs() float64 {
	if x != nil {
		return x.RetrievalLatencyMs
	}
	return 0
}

func (x *RetrieveResponse) GetTokensSavedEstimate() int64 {
	if x != nil {
		return x.TokensSavedEstimate
	}
	return 0
}

type StepResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Action        string                 `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty"`
	Outcome       string                 `protobuf:"bytes,2,opt,name=outcome,proto3" json:"outcome,omitempty"`
	TokensUsed    int32                  `protobuf:"varint,3,opt,name=tokens_used,json=tokensUsed,proto3" json:"tokens_used,omitempty"`
	DurationMs    int32                  `protobuf:"varint,4,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	Rationale     string                 `protobuf:"bytes,5,opt,name=rationale,proto3" json:"rationale,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StepResult) Reset() {
	*x = StepResult{}
	mi := &file_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StepResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StepResult) ProtoMessage() {}

func (x *StepResult) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StepResult.ProtoReflect.Descriptor instead.
func (*StepResult) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{13}
}

func (x *StepResult) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *StepResult) GetOutcome() string {
	if x != nil {
		return x.Outcome
	}
	return ""
}

func (x *StepResult) GetTokensUsed() int32 {
	if x != nil {
		return x.TokensUsed
	}
	return 0
}

func (x *StepResult) GetDurationMs() int32 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *StepResult) GetRationale() string {
	if x != nil {
		return x.Rationale
	}
	return ""
}

type RecordEpisodeRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	WorkflowId      string                 `protobuf:"bytes,1,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	RunId           string                 `protobuf:"bytes,2,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	TaskDescription string                 `protobuf:"bytes,3,opt,name=task_description,json=taskDescription,proto3" json:"task_description,omitempty"`
	StepResults     map[string]*StepResult `protobuf:"bytes,4,rep,name=step_results,json=stepResults,proto3" json:"step_results,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Inputs          *structpb.Struct       `protobuf:"bytes,5,opt,name=inputs,proto3" json:"inputs,omitempty"`
	Outputs         *structpb.Struct       `protobuf:"bytes,6,opt,name=outputs,proto3" json:"outputs,omitempty"`
	TotalTokens     int32                  `protobuf:"varint,7,opt,name=total_tokens,json=totalTokens,proto3" json:"total_tokens,omitempty"`
	TotalCost       float64                `protobuf:"fixed64,8,opt,name=total_cost,json=totalCost,proto3" json:"total_cost,omitempty"`
	DurationMs      int32                  `protobuf:"varint,9,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	ScopeType       string                 `protobuf:"bytes,10,opt,name=scope_type,json=scopeType,proto3" json:"scope_type,omitempty"`
	ScopeId         string                 `protobuf:"bytes,11,opt,name=scope_id,json=scopeId,proto3" json:"scope_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RecordEpisodeRequest) Reset() {
	*x = RecordEpisodeRequest{}
	mi := &file_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordEpisodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordEpisodeRequest) ProtoMessage() {}

func (x *RecordEpisodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordEpisodeRequest.ProtoReflect.Descriptor instead.
func (*RecordEpisodeRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{14}
}

func (x *RecordEpisodeRequest) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

func (x *RecordEpisodeRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *RecordEpisodeRequest) GetTaskDescription() string {
	if x != nil {
		return x.TaskDescription
	}
	return ""
}

func (x *RecordEpisodeRequest) GetStepResults() map[string]*StepResult {
	if x != nil {
		return x.StepResults
	}
	return nil
}

func (x *RecordEpisodeRequest) GetInputs() *structpb.Struct {
	if x != nil {
		return x.Inputs
	}
	return nil
}

func (x *RecordEpisodeRequest) GetOutputs() *structpb.Struct {
	if x != nil {
		return x.Outputs
	}
	return nil
}

func (x *RecordEpisodeRequest) GetTotalTokens() int32 {
	if x != nil {
		return x.TotalTokens
	}
	return 0
}

func (x *RecordEpisodeRequest) GetTotalCost() float64 {
	if x != nil {
		return x.TotalCost
	}
	return 0
}

func (x *RecordEpisodeRequest) GetDurationMs() int32 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *RecordEpisodeRequest) GetScopeType() string {
	if x != nil {
		return x.ScopeType
	}
	return ""
}

func (x *RecordEpisodeRequest) GetScopeId() string {
	if x != nil {
		return x.ScopeId
	}
	return ""
}

type RecordEpisodeResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	EpisodeId         string                 `protobuf:"bytes,1,opt,name=episode_id,json=episodeId,proto3" json:"episode_id,omitempty"`
	TaskType          string                 `protobuf:"bytes,2,opt,name=task_type,json=taskType,proto3" json:"task_type,omitempty"`
	CompressionRatio  float64                `protobuf:"fixed64,3,opt,name=compression_ratio,json=compressionRatio,proto3" json:"compression_ratio,omitempty"`
	InsightsExtracted int32                  `protobuf:"varint,4,opt,name=insights_extracted,json=insightsExtracted,proto3" json:"insights_extracted,omitempty"`
	TokensSaved       *TokensSaved           `protobuf:"bytes,5,opt,name=tokens_saved,json=tokensSaved,proto3" json:"tokens_saved,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RecordEpisodeResponse) Reset() {
	*x = RecordEpisodeResponse{}
	mi := &file_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordEpisodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordEpisodeResponse) ProtoMessage() {}

func (x *RecordEpisodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordEpisodeResponse.ProtoReflect.Descriptor instead.
func (*RecordEpisodeResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{15}
}

func (x *RecordEpisodeResponse) GetEpisodeId() string {
	if x != nil {
		return x.EpisodeId
	}
	return ""
}

func (x *RecordEpisodeResponse) GetTaskType() string {
	if x != nil {
		return x.TaskType
	}
	return ""
}

func (x *RecordEpisodeResponse) GetCompressionRatio() float64 {
	if x != nil {
		return x.CompressionRatio
	}
	return 0
}

func (x *RecordEpisodeResponse) GetInsightsExtracted() int32 {
	if x != nil {
		return x.InsightsExtracted
	}
	return 0
}

func (x *RecordEpisodeResponse) GetTokensSaved() *TokensSaved {
	if x != nil {
		return x.TokensSaved
	}
	return nil
}

type RecordFeedbackRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EpisodeId     string                 `protobuf:"bytes,1,opt,name=episode_id,json=episodeId,proto3" json:"episode_id,omitempty"`
	Score         float64                `protobuf:"fixed64,2,opt,name=score,proto3" json:"score,omitempty"`
	Notes         string                 `protobuf:"bytes,3,opt,name=notes,proto3" json:"notes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordFeedbackRequest) Reset() {
	*x = RecordFeedbackRequest{}
	mi := &file_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordFeedbackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordFeedbackRequest) ProtoMessage() {}

func (x *RecordFeedbackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordFeedbackRequest.ProtoReflect.Descriptor instead.
func (*RecordFeedbackRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{16}
}

func (x *RecordFeedbackRequest) GetEpisodeId() string {
	if x != nil {
		return x.EpisodeId
	}
	return ""
}

func (x *RecordFeedbackRequest) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *RecordFeedbackRequest) GetNotes() string {
	if x != nil {
		return x.Notes
	}
	return ""
}

type RecordFeedbackResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordFeedbackResponse) Reset() {
	*x = RecordFeedbackResponse{}
	mi := &file_service_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordFeedbackResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordFeedbackResponse) ProtoMessage() {}

func (x *RecordFeedbackResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordFeedbackResponse.ProtoReflect.Descriptor instead.
func (*RecordFeedbackResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{17}
}

type GetStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatsRequest) Reset() {
	*x = GetStatsRequest{}
	mi := &file_service_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatsRequest) ProtoMessage() {}

func (x *GetStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatsRequest.ProtoReflect.Descriptor instead.
func (*GetStatsRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{18}
}

type TokensSavedBySource struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	DeltaContext   int64                  `protobuf:"varint,1,opt,name=delta_context,json=deltaContext,proto3" json:"delta_context,omitempty"`
	CrossExecution int64                  `protobuf:"varint,2,opt,name=cross_execution,json=crossExecution,proto3" json:"cross_execution,omitempty"`
	Compression    int64                  `protobuf:"varint,3,opt,name=compression,proto3" json:"compression,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TokensSavedBySource) Reset() {
	*x = TokensSavedBySource{}
	mi := &file_service_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokensSavedBySource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokensSavedBySource) ProtoMessage() {}

func (x *TokensSavedBySource) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokensSavedBySource.ProtoReflect.Descriptor instead.
func (*TokensSavedBySource) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{19}
}

func (x *TokensSavedBySource) GetDeltaContext() int64 {
	if x != nil {
		return x.DeltaContext
	}
	return 0
}

func (x *TokensSavedBySource) GetCrossExecution() int64 {
	if x != nil {
		return x.CrossExecution
	}
	return 0
}

func (x *TokensSavedBySource) GetCompression() int64 {
	if x != nil {
		return x.Compression
	}
	return 0
}

type TokensSavedStats struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Total          int64                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	BySource       *TokensSavedBySource   `protobuf:"bytes,2,opt,name=by_source,json=bySource,proto3" json:"by_source,omitempty"`
	Period         string                 `protobuf:"bytes,3,opt,name=period,proto3" json:"period,omitempty"`
	CostSavingsUsd float64                `protobuf:"fixed64,4,opt,name=cost_savings_usd,json=costSavingsUsd,proto3" json:"cost_savings_usd,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TokensSavedStats) Reset() {
	*x = TokensSavedStats{}
	mi := &file_service_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokensSavedStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokensSavedStats) ProtoMessage() {}

func (x *TokensSavedStats) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokensSavedStats.ProtoReflect.Descriptor instead.
func (*TokensSavedStats) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{20}
}

func (x *TokensSavedStats) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *TokensSavedStats) GetBySource() *TokensSavedBySource {
	if x != nil {
		return x.BySource
	}
	return nil
}

func (x *TokensSavedStats) GetPeriod() string {
	if x != nil {
		return x.Period
	}
	return ""
}

func (x *TokensSavedStats) GetCostSavingsUsd() float64 {
	if x != nil {
		return x.CostSavingsUsd
	}
	return 0
}

type KnowledgeStateDistribution struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Embryonic     int32                  `protobuf:"varint,1,opt,name=embryonic,proto3" json:"embryonic,omitempty"`
	Growing       int32                  `protobuf:"varint,2,opt,name=growing,proto3" json:"growing,omitempty"`
	Mature        int32                  `protobuf:"varint,3,opt,name=mature,proto3" json:"mature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KnowledgeStateDistribution) Reset() {
	*x = KnowledgeStateDistribution{}
	mi := &file_service_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KnowledgeStateDistribution) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KnowledgeStateDistribution) ProtoMessage() {}

func (x *KnowledgeStateDistribution) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KnowledgeStateDistribution.ProtoReflect.Descriptor instead.
func (*KnowledgeStateDistribution) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{21}
}

func (x *KnowledgeStateDistribution) GetEmbryonic() int32 {
	if x != nil {
		return x.Embryonic
	}
	return 0
}

func (x *KnowledgeStateDistribution) GetGrowing() int32 {
	if x != nil {
		return x.Growing
	}
	return 0
}

func (x *KnowledgeStateDistribution) GetMature() int32 {
	if x != nil {
		return x.Mature
	}
	return 0
}

type GetStatsResponse struct {
	state                      protoimpl.MessageState      `protogen:"open.v1"`
	TotalEpisodes              int32                       `protobuf:"varint,1,opt,name=total_episodes,json=totalEpisodes,proto3" json:"total_episodes,omitempty"`
	TotalKnowledgeNodes        int32                       `protobuf:"varint,2,opt,name=total_knowledge_nodes,json=totalKnowledgeNodes,proto3" json:"total_knowledge_nodes,omitempty"`
	TotalEdges                 int32                       `protobuf:"varint,3,opt,name=total_edges,json=totalEdges,proto3" json:"total_edges,omitempty"`
	CompressionRatioAvg        float64                     `protobuf:"fixed64,4,opt,name=compression_ratio_avg,json=compressionRatioAvg,proto3" json:"compression_ratio_avg,omitempty"`
	TokensSaved                *TokensSavedStats           `protobuf:"bytes,5,opt,name=tokens_saved,json=tokensSaved,proto3" json:"tokens_saved,omitempty"`
	ActiveSessions             int32                       `protobuf:"varint,6,opt,name=active_sessions,json=activeSessions,proto3" json:"active_sessions,omitempty"`
	LastConsolidationAt        *timestamppb.Timestamp      `protobuf:"bytes,7,opt,name=last_consolidation_at,json=lastConsolidationAt,proto3" json:"last_consolidation_at,omitempty"`
	KnowledgeStateDistribution *KnowledgeStateDistribution `protobuf:"bytes,8,opt,name=knowledge_state_distribution,json=knowledgeStateDistribution,proto3" json:"knowledge_state_distribution,omitempty"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *GetStatsResponse) Reset() {
	*x = GetStatsResponse{}
	mi := &file_service_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatsResponse) ProtoMessage() {}

func (x *GetStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatsResponse.ProtoReflect.Descriptor instead.
func (*GetStatsResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{22}
}

func (x *GetStatsResponse) GetTotalEpisodes() int32 {
	if x != nil {
		return x.TotalEpisodes
	}
	return 0
}

func (x *GetStatsResponse) GetTotalKnowledgeNodes() int32 {
	if x != nil {
		return x.TotalKnowledgeNodes
	}
	return 0
}

func (x *GetStatsResponse) GetTotalEdges() int32 {
	if x != nil {
		return x.TotalEdges
	}
	return 0
}

func (x *GetStatsResponse) GetCompressionRatioAvg() float64 {
	if x != nil {
		return x.CompressionRatioAvg
	}
	return 0
}

func (x *GetStatsResponse) GetTokensSaved() *TokensSavedStats {
	if x != nil {
		return x.TokensSaved
	}
	return nil
}

func (x *GetStatsResponse) GetActiveSessions() int32 {
	if x != nil {
		return x.ActiveSessions
	}
	return 0
}

func (x *GetStatsResponse) GetLastConsolidationAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastConsolidationAt
	}
	return nil
}

func (x *GetStatsResponse) GetKnowledgeStateDistribution() *KnowledgeStateDistribution {
	if x != nil {
		return x.KnowledgeStateDistribution
	}
	return nil
}

type TriggerConsolidationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TriggerConsolidationRequest) Reset() {
	*x = TriggerConsolidationRequest{}
	mi := &file_service_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerConsolidationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerConsolidationRequest) ProtoMessage() {}

func (x *TriggerConsolidationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerConsolidationRequest.ProtoReflect.Descriptor instead.
func (*TriggerConsolidationRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{23}
}

type TriggerConsolidationResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ConsolidationId string                 `protobuf:"bytes,1,opt,name=consolidation_id,json=consolidationId,proto3" json:"consolidation_id,omitempty"`
	Status          string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	EpisodesQueued  int32                  `protobuf:"varint,3,opt,name=episodes_queued,json=episodesQueued,proto3" json:"episodes_queued,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TriggerConsolidationResponse) Reset() {
	*x = TriggerConsolidationResponse{}
	mi := &file_service_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerConsolidationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerConsolidationResponse) ProtoMessage() {}

func (x *TriggerConsolidationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerConsolidationResponse.ProtoReflect.Descriptor instead.
func (*TriggerConsolidationResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{24}
}

func (x *TriggerConsolidationResponse) GetConsolidationId() string {
	if x != nil {
		return x.ConsolidationId
	}
	return ""
}

func (x *TriggerConsolidationResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *TriggerConsolidationResponse) GetEpisodesQueued() int32 {
	if x != nil {
		return x.EpisodesQueued
	}
	return 0
}

type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_service_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{25}
}

type ServiceHealth struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Aurora        string                 `protobuf:"bytes,1,opt,name=aurora,proto3" json:"aurora,omitempty"`
	Redis         string                 `protobuf:"bytes,2,opt,name=redis,proto3" json:"redis,omitempty"`
	Neo4J         string                 `protobuf:"bytes,3,opt,name=neo4j,proto3" json:"neo4j,omitempty"`
	Pgvector      string                 `protobuf:"bytes,4,opt,name=pgvector,proto3" json:"pgvector,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceHealth) Reset() {
	*x = ServiceHealth{}
	mi := &file_service_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceHealth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceHealth) ProtoMessage() {}

func (x *ServiceHealth) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceHealth.ProtoReflect.Descriptor instead.
func (*ServiceHealth) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{26}
}

func (x *ServiceHealth) GetAurora() string {
	if x != nil {
		return x.Aurora
	}
	return ""
}

func (x *ServiceHealth) GetRedis() string {
	if x != nil {
		return x.Redis
	}
	return ""
}

func (x *ServiceHealth) GetNeo4J() string {
	if x != nil {
		return x.Neo4J
	}
	return ""
}

func (x *ServiceHealth) GetPgvector() string {
	if x != nil {
		return x.Pgvector
	}
	return ""
}

type HealthCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Services      *ServiceHealth         `protobuf:"bytes,3,opt,name=services,proto3" json:"services,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_service_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{27}
}

func (x *HealthCheckResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthCheckResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *HealthCheckResponse) GetServices() *ServiceHealth {
	if x != nil {
		return x.Services
	}
	return nil
}

var File_service_proto protoreflect.FileDescriptor

const file_service_proto_rawDesc = "" +
	"\n" +
	"\rservice.proto\x12\vhivemind.v1\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"Z\n" +
	"\bPlanStep\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x05R\x05index\x12\x16\n" +
	"\x06action\x18\x02 \x01(\tR\x06action\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\"X\n" +
	"\x04Plan\x12+\n" +
	"\x05steps\x18\x01 \x03(\v2\x15.hivemind.v1.PlanStepR\x05steps\x12#\n" +
	"\rcurrent_index\x18\x02 \x01(\x05R\fcurrentIndex\"\xa9\x01\n" +
	"\x13StartSessionRequest\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12\x1f\n" +
	"\vworkflow_id\x18\x02 \x01(\tR\n" +
	"workflowId\x12\x12\n" +
	"\x04task\x18\x03 \x01(\tR\x04task\x12%\n" +
	"\x04plan\x18\x04 \x01(\v2\x11.hivemind.v1.PlanR\x04plan\x12\x1f\n" +
	"\vhivemind_id\x18\x05 \x01(\tR\n" +
	"hivemindId\"\xa1\x01\n" +
	"\x14StartSessionResponse\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12\x1f\n" +
	"\vhivemind_id\x18\x02 \x01(\tR\n" +
	"hivemindId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"p\n" +
	"\x14UpdateContextRequest\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12\x14\n" +
	"\x05field\x18\x02 \x01(\tR\x05field\x12+\n" +
	"\x04data\x18\x03 \x01(\v2\x17.google.protobuf.StructR\x04data\"\x17\n" +
	"\x15UpdateContextResponse\"\xb6\x01\n" +
	"\x17GetContextWindowRequest\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12\x19\n" +
	"\bagent_id\x18\x02 \x01(\tR\aagentId\x12\x1d\n" +
	"\n" +
	"max_tokens\x18\x03 \x01(\x05R\tmaxTokens\x12'\n" +
	"\x0fconversation_id\x18\x04 \x01(\tR\x0econversationId\x12!\n" +
	"\fcontext_mode\x18\x05 \x01(\tR\vcontextMode\"\xf3\x01\n" +
	"\x18GetContextWindowResponse\x12\x18\n" +
	"\acontext\x18\x01 \x01(\tR\acontext\x12\x1b\n" +
	"\tmode_used\x18\x02 \x01(\tR\bmodeUsed\x12\x1f\n" +
	"\vturn_number\x18\x03 \x01(\x05R\n" +
	"turnNumber\x12!\n" +
	"\ftotal_tokens\x18\x04 \x01(\x05R\vtotalTokens\x12,\n" +
	"\x12delta_tokens_saved\x18\x05 \x01(\x05R\x10deltaTokensSaved\x12.\n" +
	"\x13full_context_tokens\x18\x06 \x01(\x05R\x11fullContextTokens\"*\n" +
	"\x11EndSessionRequest\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\"}\n" +
	"\vTokensSaved\x12#\n" +
	"\rdelta_context\x18\x01 \x01(\x03R\fdeltaContext\x12 \n" +
	"\vcompression\x18\x02 \x01(\x03R\vcompression\x12'\n" +
	"\x0fcross_execution\x18\x03 \x01(\x03R\x0ecrossExecution\"\x91\x02\n" +
	"\x12EndSessionResponse\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"episode_id\x18\x03 \x01(\tR\tepisodeId\x12)\n" +
	"\x10recording_status\x18\x04 \x01(\tR\x0frecordingStatus\x12+\n" +
	"\x11compression_ratio\x18\x05 \x01(\x01R\x10compressionRatio\x12;\n" +
	"\ftokens_saved\x18\x06 \x01(\v2\x18.hivemind.v1.TokensSavedR\vtokensSaved\x12\x18\n" +
	"\awarning\x18\a \x01(\tR\awarning\"\xa9\x02\n" +
	"\x0fRetrieveRequest\x12\x16\n" +
	"\x06intent\x18\x01 \x01(\tR\x06intent\x12\x1b\n" +
	"\ttask_type\x18\x02 \x01(\tR\btaskType\x12 \n" +
	"\vconstraints\x18\x03 \x03(\tR\vconstraints\x12\x1d\n" +
	"\n" +
	"max_tokens\x18\x04 \x01(\x05R\tmaxTokens\x12\x14\n" +
	"\x05depth\x18\x05 \x01(\x05R\x05depth\x12%\n" +
	"\x0emin_confidence\x18\x06 \x01(\x01R\rminConfidence\x12\x1d\n" +
	"\n" +
	"scope_type\x18\a \x01(\tR\tscopeType\x12\x19\n" +
	"\bscope_id\x18\b \x01(\tR\ascopeId\x12)\n" +
	"\x10include_unscoped\x18\t \x01(\bR\x0fincludeUnscoped\"\xd4\x02\n" +
	"\x10RetrieveResponse\x12!\n" +
	"\fcontext_text\x18\x01 \x01(\tR\vcontextText\x12%\n" +
	"\x0econtext_tokens\x18\x02 \x01(\x05R\rcontextTokens\x12\x1f\n" +
	"\vbudget_used\x18\x03 \x01(\x01R\n" +
	"budgetUsed\x12!\n" +
	"\fskills_count\x18\x04 \x01(\x05R\vskillsCount\x12%\n" +
	"\x0epatterns_count\x18\x05 \x01(\x05R\rpatternsCount\x12%\n" +
	"\x0eepisodes_count\x18\x06 \x01(\x05R\repisodesCount\x120\n" +
	"\x14retrieval_latency_ms\x18\a \x01(\x01R\x12retrievalLatencyMs\x122\n" +
	"\x15tokens_saved_estimate\x18\b \x01(\x03R\x13tokensSavedEstimate\"\x9e\x01\n" +
	"\n" +
	"StepResult\x12\x16\n" +
	"\x06action\x18\x01 \x01(\tR\x06action\x12\x18\n" +
	"\aoutcome\x18\x02 \x01(\tR\aoutcome\x12\x1f\n" +
	"\vtokens_used\x18\x03 \x01(\x05R\n" +
	"tokensUsed\x12\x1f\n" +
	"\vduration_ms\x18\x04 \x01(\x05R\n" +
	"durationMs\x12\x1c\n" +
	"\trationale\x18\x05 \x01(\tR\trationale\"\xaa\x04\n" +
	"\x14RecordEpisodeRequest\x12\x1f\n" +
	"\vworkflow_id\x18\x01 \x01(\tR\n" +
	"workflowId\x12\x15\n" +
	"\x06run_id\x18\x02 \x01(\tR\x05runId\x12)\n" +
	"\x10task_description\x18\x03 \x01(\tR\x0ftaskDescription\x12U\n" +
	"\fstep_results\x18\x04 \x03(\v22.hivemind.v1.RecordEpisodeRequest.StepResultsEntryR\vstepResults\x12/\n" +
	"\x06inputs\x18\x05 \x01(\v2\x17.google.protobuf.StructR\x06inputs\x121\n" +
	"\aoutputs\x18\x06 \x01(\v2\x17.google.protobuf.StructR\aoutputs\x12!\n" +
	"\ftotal_tokens\x18\a \x01(\x05R\vtotalTokens\x12\x1d\n" +
	"\n" +
	"total_cost\x18\b \x01(\x01R\ttotalCost\x12\x1f\n" +
	"\vduration_ms\x18\t \x01(\x05R\n" +
	"durationMs\x12\x1d\n" +
	"\n" +
	"scope_type\x18\n" +
	" \x01(\tR\tscopeType\x12\x19\n" +
	"\bscope_id\x18\v \x01(\tR\ascopeId\x1aW\n" +
	"\x10StepResultsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12-\n" +
	"\x05value\x18\x02 \x01(\v2\x17.hivemind.v1.StepResultR\x05value:\x028\x01\"\xec\x01\n" +
	"\x15RecordEpisodeResponse\x12\x1d\n" +
	"\n" +
	"episode_id\x18\x01 \x01(\tR\tepisodeId\x12\x1b\n" +
	"\ttask_type\x18\x02 \x01(\tR\btaskType\x12+\n" +
	"\x11compression_ratio\x18\x03 \x01(\x01R\x10compressionRatio\x12-\n" +
	"\x12insights_extracted\x18\x04 \x01(\x05R\x11insightsExtracted\x12;\n" +
	"\ftokens_saved\x18\x05 \x01(\v2\x18.hivemind.v1.TokensSavedR\vtokensSaved\"b\n" +
	"\x15RecordFeedbackRequest\x12\x1d\n" +
	"\n" +
	"episode_id\x18\x01 \x01(\tR\tepisodeId\x12\x14\n" +
	"\x05score\x18\x02 \x01(\x01R\x05score\x12\x14\n" +
	"\x05notes\x18\x03 \x01(\tR\x05notes\"\x18\n" +
	"\x16RecordFeedbackResponse\"\x11\n" +
	"\x0fGetStatsRequest\"\x85\x01\n" +
	"\x13TokensSavedBySource\x12#\n" +
	"\rdelta_context\x18\x01 \x01(\x03R\fdeltaContext\x12'\n" +
	"\x0fcross_execution\x18\x02 \x01(\x03R\x0ecrossExecution\x12 \n" +
	"\vcompression\x18\x03 \x01(\x03R\vcompression\"\xa9\x01\n" +
	"\x10TokensSavedStats\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x03R\x05total\x12=\n" +
	"\tby_source\x18\x02 \x01(\v2 .hivemind.v1.TokensSavedBySourceR\bbySource\x12\x16\n" +
	"\x06period\x18\x03 \x01(\tR\x06period\x12(\n" +
	"\x10cost_savings_usd\x18\x04 \x01(\x01R\x0ecostSavingsUsd\"l\n" +
	"\x1aKnowledgeStateDistribution\x12\x1c\n" +
	"\tembryonic\x18\x01 \x01(\x05R\tembryonic\x12\x18\n" +
	"\agrowing\x18\x02 \x01(\x05R\agrowing\x12\x16\n" +
	"\x06mature\x18\x03 \x01(\x05R\x06mature\"\xe8\x03\n" +
	"\x10GetStatsResponse\x12%\n" +
	"\x0etotal_episodes\x18\x01 \x01(\x05R\rtotalEpisodes\x122\n" +
	"\x15total_knowledge_nodes\x18\x02 \x01(\x05R\x13totalKnowledgeNodes\x12\x1f\n" +
	"\vtotal_edges\x18\x03 \x01(\x05R\n" +
	"totalEdges\x122\n" +
	"\x15compression_ratio_avg\x18\x04 \x01(\x01R\x13compressionRatioAvg\x12@\n" +
	"\ftokens_saved\x18\x05 \x01(\v2\x1d.hivemind.v1.TokensSavedStatsR\vtokensSaved\x12'\n" +
	"\x0factive_sessions\x18\x06 \x01(\x05R\x0eactiveSessions\x12N\n" +
	"\x15last_consolidation_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\x13lastConsolidationAt\x12i\n" +
	"\x1cknowledge_state_distribution\x18\b \x01(\v2'.hivemind.v1.KnowledgeStateDistributionR\x1aknowledgeStateDistribution\"\x1d\n" +
	"\x1bTriggerConsolidationRequest\"\x8a\x01\n" +
	"\x1cTriggerConsolidationResponse\x12)\n" +
	"\x10consolidation_id\x18\x01 \x01(\tR\x0fconsolidationId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12'\n" +
	"\x0fepisodes_queued\x18\x03 \x01(\x05R\x0eepisodesQueued\"\x14\n" +
	"\x12HealthCheckRequest\"o\n" +
	"\rServiceHealth\x12\x16\n" +
	"\x06aurora\x18\x01 \x01(\tR\x06aurora\x12\x14\n" +
	"\x05redis\x18\x02 \x01(\tR\x05redis\x12\x14\n" +
	"\x05neo4j\x18\x03 \x01(\tR\x05neo4j\x12\x1a\n" +
	"\bpgvector\x18\x04 \x01(\tR\bpgvector\"\x7f\n" +
	"\x13HealthCheckResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x126\n" +
	"\bservices\x18\x03 \x01(\v2\x1a.hivemind.v1.ServiceHealthR\bservices2\xf2\x06\n" +
	"\x0fHivemindService\x12S\n" +
	"\fStartSession\x12 .hivemind.v1.StartSessionRequest\x1a!.hivemind.v1.StartSessionResponse\x12V\n" +
	"\rUpdateContext\x12!.hivemind.v1.UpdateContextRequest\x1a\".hivemind.v1.UpdateContextResponse\x12_\n" +
	"\x10GetContextWindow\x12$.hivemind.v1.GetContextWindowRequest\x1a%.hivemind.v1.GetContextWindowResponse\x12M\n" +
	"\n" +
	"EndSession\x12\x1e.hivemind.v1.EndSessionRequest\x1a\x1f.hivemind.v1.EndSessionResponse\x12G\n" +
	"\bRetrieve\x12\x1c.hivemind.v1.RetrieveRequest\x1a\x1d.hivemind.v1.RetrieveResponse\x12V\n" +
	"\rRecordEpisode\x12!.hivemind.v1.RecordEpisodeRequest\x1a\".hivemind.v1.RecordEpisodeResponse\x12Y\n" +
	"\x0eRecordFeedback\x12\".hivemind.v1.RecordFeedbackRequest\x1a#.hivemind.v1.RecordFeedbackResponse\x12G\n" +
	"\bGetStats\x12\x1c.hivemind.v1.GetStatsRequest\x1a\x1d.hivemind.v1.GetStatsResponse\x12k\n" +
	"\x14TriggerConsolidation\x12(.hivemind.v1.TriggerConsolidationRequest\x1a).hivemind.v1.TriggerConsolidationResponse\x12P\n" +
	"\vHealthCheck\x12\x1f.hivemind.v1.HealthCheckRequest\x1a .hivemind.v1.HealthCheckResponseB:Z8github.com/smartify-inc/hivemind-go-sdk/proto/hivemindv1b\x06proto3"

var (
	file_service_proto_rawDescOnce sync.Once
	file_service_proto_rawDescData []byte
)

func file_service_proto_rawDescGZIP() []byte {
	file_service_proto_rawDescOnce.Do(func() {
		file_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_service_proto_rawDesc), len(file_service_proto_rawDesc)))
	})
	return file_service_proto_rawDescData
}

var file_service_proto_msgTypes = make([]protoimpl.MessageInfo, 29)
var file_service_proto_goTypes = []any{
	(*PlanStep)(nil),                     // 0: hivemind.v1.PlanStep
	(*Plan)(nil),                         // 1: hivemind.v1.Plan
	(*StartSessionRequest)(nil),          // 2: hivemind.v1.StartSessionRequest
	(*StartSessionResponse)(nil),         // 3: hivemind.v1.StartSessionResponse
	(*UpdateContextRequest)(nil),         // 4: hivemind.v1.UpdateContextRequest
	(*UpdateContextResponse)(nil),        // 5: hivemind.v1.UpdateContextResponse
	(*GetContextWindowRequest)(nil),      // 6: hivemind.v1.GetContextWindowRequest
	(*GetContextWindowResponse)(nil),     // 7: hivemind.v1.GetContextWindowResponse
	(*EndSessionRequest)(nil),            // 8: hivemind.v1.EndSessionRequest
	(*TokensSaved)(nil),                  // 9: hivemind.v1.TokensSaved
	(*EndSessionResponse)(nil),           // 10: hivemind.v1.EndSessionResponse
	(*RetrieveRequest)(nil),              // 11: hivemind.v1.RetrieveRequest
	(*RetrieveResponse)(nil),             // 12: hivemind.v1.RetrieveResponse
	(*StepResult)(nil),                   // 13: hivemind.v1.StepResult
	(*RecordEpisodeRequest)(nil),         // 14: hivemind.v1.RecordEpisodeRequest
	(*RecordEpisodeResponse)(nil),        // 15: hivemind.v1.RecordEpisodeResponse
	(*RecordFeedbackRequest)(nil),        // 16: hivemind.v1.RecordFeedbackRequest
	(*RecordFeedbackResponse)(nil),       // 17: hivemind.v1.RecordFeedbackResponse
	(*GetStatsRequest)(nil),              // 18: hivemind.v1.GetStatsRequest
	(*TokensSavedBySource)(nil),          // 19: hivemind.v1.TokensSavedBySource
	(*TokensSavedStats)(nil),             // 20: hivemind.v1.TokensSavedStats
	(*KnowledgeStateDistribution)(nil),   // 21: hivemind.v1.KnowledgeStateDistribution
	(*GetStatsResponse)(nil),             // 22: hivemind.v1.GetStatsResponse
	(*TriggerConsolidationRequest)(nil),  // 23: hivemind.v1.TriggerConsolidationRequest
	(*TriggerConsolidationResponse)(nil), // 24: hivemind.v1.TriggerConsolidationResponse
	(*HealthCheckRequest)(nil),           // 25: hivemind.v1.HealthCheckRequest
	(*ServiceHealth)(nil),                // 26: hivemind.v1.ServiceHealth
	(*HealthCheckResponse)(nil),          // 27: hivemind.v1.HealthCheckResponse
	nil,                                  // 28: hivemind.v1.RecordEpisodeRequest.StepResultsEntry
	(*timestamppb.Timestamp)(nil),        // 29: google.protobuf.Timestamp
	(*structpb.Struct)(nil),              // 30: google.protobuf.Struct
}
var file_service_proto_depIdxs = []int32{
	0,  // 0: hivemind.v1.Plan.steps:type_name -> hivemind.v1.PlanStep
	1,  // 1: hivemind.v1.StartSessionRequest.plan:type_name -> hivemind.v1.Plan
	29, // 2: hivemind.v1.StartSessionResponse.created_at:type_name -> google.protobuf.Timestamp
	30, // 3: hivemind.v1.UpdateContextRequest.data:type_name -> google.protobuf.Struct
	9,  // 4: hivemind.v1.EndSessionResponse.tokens_saved:type_name -> hivemind.v1.TokensSaved
	28, // 5: hivemind.v1.RecordEpisodeRequest.step_results:type_name -> hivemind.v1.RecordEpisodeRequest.StepResultsEntry
	30, // 6: hivemind.v1.RecordEpisodeRequest.inputs:type_name -> google.protobuf.Struct
	30, // 7: hivemind.v1.RecordEpisodeRequest.outputs:type_name -> google.protobuf.Struct
	9,  // 8: hivemind.v1.RecordEpisodeResponse.tokens_saved:type_name -> hivemind.v1.TokensSaved
	19, // 9: hivemind.v1.TokensSavedStats.by_source:type_name -> hivemind.v1.TokensSavedBySource
	20, // 10: hivemind.v1.GetStatsResponse.tokens_saved:type_name -> hivemind.v1.TokensSavedStats
	29, // 11: hivemind.v1.GetStatsResponse.last_consolidation_at:type_name -> google.protobuf.Timestamp
	21, // 12: hivemind.v1.GetStatsResponse.knowledge_state_distribution:type_name -> hivemind.v1.KnowledgeStateDistribution
	26, // 13: hivemind.v1.HealthCheckResponse.services:type_name -> hivemind.v1.ServiceHealth
	13, // 14: hivemind.v1.RecordEpisodeRequest.StepResultsEntry.value:type_name -> hivemind.v1.StepResult
	2,  // 15: hivemind.v1.HivemindService.StartSession:input_type -> hivemind.v1.StartSessionRequest
	4,  // 16: hivemind.v1.HivemindService.UpdateContext:input_type -> hivemind.v1.UpdateContextRequest
	6,  // 17: hivemind.v1.HivemindService.GetContextWindow:input_type -> hivemind.v1.GetContextWindowRequest
	8,  // 18: hivemind.v1.HivemindService.EndSession:input_type -> hivemind.v1.EndSessionRequest
	11, // 19: hivemind.v1.HivemindService.Retrieve:input_type -> hivemind.v1.RetrieveRequest
	14, // 20: hivemind.v1.HivemindService.RecordEpisode:input_type -> hivemind.v1.RecordEpisodeRequest
	16, // 21: hivemind.v1.HivemindService.RecordFeedback:input_type -> hivemind.v1.RecordFeedbackRequest
	18, // 22: hivemind.v1.HivemindService.GetStats:input_type -> hivemind.v1.GetStatsRequest
	23, // 23: hivemind.v1.HivemindService.TriggerConsolidation:input_type -> hivemind.v1.TriggerConsolidationRequest
	25, // 24: hivemind.v1.HivemindService.HealthCheck:input_type -> hivemind.v1.HealthCheckRequest
	3,  // 25: hivemind.v1.HivemindService.StartSession:output_type -> hivemind.v1.StartSessionResponse
	5,  // 26: hivemind.v1.HivemindService.UpdateContext:output_type -> hivemind.v1.UpdateContextResponse
	7,  // 27: hivemind.v1.HivemindService.GetContextWindow:output_type -> hivemind.v1.GetContextWindowResponse
	10, // 28: hivemind.v1.HivemindService.EndSession:output_type -> hivemind.v1.EndSessionResponse
	12, // 29: hivemind.v1.HivemindService.Retrieve:output_type -> hivemind.v1.RetrieveResponse
	15, // 30: hivemind.v1.HivemindService.RecordEpisode:output_type -> hivemind.v1.RecordEpisodeResponse
	17, // 31: hivemind.v1.HivemindService.RecordFeedback:output_type -> hivemind.v1.RecordFeedbackResponse
	22, // 32: hivemind.v1.HivemindService.GetStats:output_type -> hivemind.v1.GetStatsResponse
	24, // 33: hivemind.v1.HivemindService.TriggerConsolidation:output_type -> hivemind.v1.TriggerConsolidationResponse
	27, // 34: hivemind.v1.HivemindService.HealthCheck:output_type -> hivemind.v1.HealthCheckResponse
	25, // [25:35] is the sub-list for method output_type
	15, // [15:25] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_service_proto_init() }
func file_service_proto_init() {
	if File_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_proto_rawDesc), len(file_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   29,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_proto_goTypes,
		DependencyIndexes: file_service_proto_depIdxs,
		MessageInfos:      file_service_proto_msgTypes,
	}.Build()
	File_service_proto = out.File
	file_service_proto_goTypes = nil
	file_service_proto_depIdxs = nil
}
