// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.4
// source: service.proto

package hivemindv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	HivemindService_StartSession_FullMethodName         = "/hivemind.v1.HivemindService/StartSession"
	HivemindService_UpdateContext_FullMethodName        = "/hivemind.v1.HivemindService/UpdateContext"
	HivemindService_GetContextWindow_FullMethodName     = "/hivemind.v1.HivemindService/GetContextWindow"
	HivemindService_EndSession_FullMethodName           = "/hivemind.v1.HivemindService/EndSession"
	HivemindService_Retrieve_FullMethodName             = "/hivemind.v1.HivemindService/Retrieve"
	HivemindService_RecordEpisode_FullMethodName        = "/hivemind.v1.HivemindService/RecordEpisode"
	HivemindService_RecordFeedback_FullMethodName       = "/hivemind.v1.HivemindService/RecordFeedback"
	HivemindService_GetStats_FullMethodName             = "/hivemind.v1.HivemindService/GetStats"
	HivemindService_TriggerConsolidation_FullMethodName = "/hivemind.v1.HivemindService/TriggerConsolidation"
	HivemindService_HealthCheck_FullMethodName          = "/hivemind.v1.HivemindService/HealthCheck"
)

// HivemindServiceClient is the client API for HivemindService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HivemindServiceClient interface {
	StartSession(ctx context.Context, in *StartSessionRequest, opts ...grpc.CallOption) (*StartSessionResponse, error)
	UpdateContext(ctx context.Context, in *UpdateContextRequest, opts ...grpc.CallOption) (*UpdateContextResponse, error)
	GetContextWindow(ctx context.Context, in *GetContextWindowRequest, opts ...grpc.CallOption) (*GetContextWindowResponse, error)
	EndSession(ctx context.Context, in *EndSessionRequest, opts ...grpc.CallOption) (*EndSessionResponse, error)
	Retrieve(ctx context.Context, in *RetrieveRequest, opts ...grpc.CallOption) (*RetrieveResponse, error)
	RecordEpisode(ctx context.Context, in *RecordEpisodeRequest, opts ...grpc.CallOption) (*RecordEpisodeResponse, error)
	RecordFeedback(ctx context.Context, in *RecordFeedbackRequest, opts ...grpc.CallOption) (*RecordFeedbackResponse, error)
	GetStats(ctx context.Context, in *GetStatsRequest, opts ...grpc.CallOption) (*GetStatsResponse, error)
	TriggerConsolidation(ctx context.Context, in *TriggerConsolidationRequest, opts ...grpc.CallOption) (*TriggerConsolidationResponse, error)
	HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
}

type hivemindServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewHivemindServiceClient(cc grpc.ClientConnInterface) HivemindServiceClient {
	return &hivemindServiceClient{cc}
}

func (c *hivemindServiceClient) StartSession(ctx context.Context, in *StartSessionRequest, opts ...grpc.CallOption) (*StartSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartSessionResponse)
	err := c.cc.Invoke(ctx, HivemindService_StartSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hivemindServiceClient) UpdateContext(ctx context.Context, in *UpdateContextRequest, opts ...grpc.CallOption) (*UpdateContextResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateContextResponse)
	err := c.cc.Invoke(ctx, HivemindService_UpdateContext_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hivemindServiceClient) GetContextWindow(ctx context.Context, in *GetContextWindowRequest, opts ...grpc.CallOption) (*GetContextWindowResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetContextWindowResponse)
	err := c.cc.Invoke(ctx, HivemindService_GetContextWindow_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hivemindServiceClient) EndSession(ctx context.Context, in *EndSessionRequest, opts ...grpc.CallOption) (*EndSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EndSessionResponse)
	err := c.cc.Invoke(ctx, HivemindService_EndSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hivemindServiceClient) Retrieve(ctx context.Context, in *RetrieveRequest, opts ...grpc.CallOption) (*RetrieveResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RetrieveResponse)
	err := c.cc.Invoke(ctx, HivemindService_Retrieve_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hivemindServiceClient) RecordEpisode(ctx context.Context, in *RecordEpisodeRequest, opts ...grpc.CallOption) (*RecordEpisodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RecordEpisodeResponse)
	err := c.cc.Invoke(ctx, HivemindService_RecordEpisode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hivemindServiceClient) RecordFeedback(ctx context.Context, in *RecordFeedbackRequest, opts ...grpc.CallOption) (*RecordFeedbackResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RecordFeedbackResponse)
	err := c.cc.Invoke(ctx, HivemindService_RecordFeedback_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hivemindServiceClient) GetStats(ctx context.Context, in *GetStatsRequest, opts ...grpc.CallOption) (*GetStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStatsResponse)
	err := c.cc.Invoke(ctx, HivemindService_GetStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hivemindServiceClient) TriggerConsolidation(ctx context.Context, in *TriggerConsolidationRequest, opts ...grpc.CallOption) (*TriggerConsolidationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TriggerConsolidationResponse)
	err := c.cc.Invoke(ctx, HivemindService_TriggerConsolidation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hivemindServiceClient) HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, HivemindService_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HivemindServiceServer is the server API for HivemindService service.
// All implementations must embed UnimplementedHivemindServiceServer
// for forward compatibility.
type HivemindServiceServer interface {
	StartSession(context.Context, *StartSessionRequest) (*StartSessionResponse, error)
	UpdateContext(context.Context, *UpdateContextRequest) (*UpdateContextResponse, error)
	GetContextWindow(context.Context, *GetContextWindowRequest) (*GetContextWindowResponse, error)
	EndSession(context.Context, *EndSessionRequest) (*EndSessionResponse, error)
	Retrieve(context.Context, *RetrieveRequest) (*RetrieveResponse, error)
	RecordEpisode(context.Context, *RecordEpisodeRequest) (*RecordEpisodeResponse, error)
	RecordFeedback(context.Context, *RecordFeedbackRequest) (*RecordFeedbackResponse, error)
	GetStats(context.Context, *GetStatsRequest) (*GetStatsResponse, error)
	TriggerConsolidation(context.Context, *TriggerConsolidationRequest) (*TriggerConsolidationResponse, error)
	HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	mustEmbedUnimplementedHivemindServiceServer()
}

// UnimplementedHivemindServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHivemindServiceServer struct{}

func (UnimplementedHivemindServiceServer) StartSession(context.Context, *StartSessionRequest) (*StartSessionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StartSession not implemented")
}
func (UnimplementedHivemindServiceServer) UpdateContext(context.Context, *UpdateContextRequest) (*UpdateContextResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateContext not implemented")
}
func (UnimplementedHivemindServiceServer) GetContextWindow(context.Context, *GetContextWindowRequest) (*GetContextWindowResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetContextWindow not implemented")
}
func (UnimplementedHivemindServiceServer) EndSession(context.Context, *EndSessionRequest) (*EndSessionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EndSession not implemented")
}
func (UnimplementedHivemindServiceServer) Retrieve(context.Context, *RetrieveRequest) (*RetrieveResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Retrieve not implemented")
}
func (UnimplementedHivemindServiceServer) RecordEpisode(context.Context, *RecordEpisodeRequest) (*RecordEpisodeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RecordEpisode not implemented")
}
func (UnimplementedHivemindServiceServer) RecordFeedback(context.Context, *RecordFeedbackRequest) (*RecordFeedbackResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RecordFeedback not implemented")
}
func (UnimplementedHivemindServiceServer) GetStats(context.Context, *GetStatsRequest) (*GetStatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStats not implemented")
}
func (UnimplementedHivemindServiceServer) TriggerConsolidation(context.Context, *TriggerConsolidationRequest) (*TriggerConsolidationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TriggerConsolidation not implemented")
}
func (UnimplementedHivemindServiceServer) HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedHivemindServiceServer) mustEmbedUnimplementedHivemindServiceServer() {}
func (UnimplementedHivemindServiceServer) testEmbeddedByValue()                         {}

// UnsafeHivemindServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HivemindServiceServer will
// result in compilation errors.
type UnsafeHivemindServiceServer interface {
	mustEmbedUnimplementedHivemindServiceServer()
}

func RegisterHivemindServiceServer(s grpc.ServiceRegistrar, srv HivemindServiceServer) {
	// If the following call panics, it indicates UnimplementedHivemindServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&HivemindService_ServiceDesc, srv)
}

func _HivemindService_StartSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HivemindServiceServer).StartSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HivemindService_StartSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HivemindServiceServer).StartSession(ctx, req.(*StartSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HivemindService_UpdateContext_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateContextRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HivemindServiceServer).UpdateContext(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HivemindService_UpdateContext_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HivemindServiceServer).UpdateContext(ctx, req.(*UpdateContextRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HivemindService_GetContextWindow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetContextWindowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HivemindServiceServer).GetContextWindow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HivemindService_GetContextWindow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HivemindServiceServer).GetContextWindow(ctx, req.(*GetContextWindowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HivemindService_EndSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EndSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HivemindServiceServer).EndSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HivemindService_EndSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HivemindServiceServer).EndSession(ctx, req.(*EndSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HivemindService_Retrieve_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RetrieveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HivemindServiceServer).Retrieve(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HivemindService_Retrieve_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HivemindServiceServer).Retrieve(ctx, req.(*RetrieveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HivemindService_RecordEpisode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecordEpisodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HivemindServiceServer).RecordEpisode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HivemindService_RecordEpisode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HivemindServiceServer).RecordEpisode(ctx, req.(*RecordEpisodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HivemindService_RecordFeedback_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecordFeedbackRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HivemindServiceServer).RecordFeedback(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HivemindService_RecordFeedback_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HivemindServiceServer).RecordFeedback(ctx, req.(*RecordFeedbackRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HivemindService_GetStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HivemindServiceServer).GetStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HivemindService_GetStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HivemindServiceServer).GetStats(ctx, req.(*GetStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HivemindService_TriggerConsolidation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TriggerConsolidationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HivemindServiceServer).TriggerConsolidation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HivemindService_TriggerConsolidation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HivemindServiceServer).TriggerConsolidation(ctx, req.(*TriggerConsolidationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HivemindService_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HivemindServiceServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HivemindService_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HivemindServiceServer).HealthCheck(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// HivemindService_ServiceDesc is the grpc.ServiceDesc for HivemindService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HivemindService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "hivemind.v1.HivemindService",
	HandlerType: (*HivemindServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartSession",
			Handler:    _HivemindService_StartSession_Handler,
		},
		{
			MethodName: "UpdateContext",
			Handler:    _HivemindService_UpdateContext_Handler,
		},
		{
			MethodName: "GetContextWindow",
			Handler:    _HivemindService_GetContextWindow_Handler,
		},
		{
			MethodName: "EndSession",
			Handler:    _HivemindService_EndSession_Handler,
		},
		{
			MethodName: "Retrieve",
			Handler:    _HivemindService_Retrieve_Handler,
		},
		{
			MethodName: "RecordEpisode",
			Handler:    _HivemindService_RecordEpisode_Handler,
		},
		{
			MethodName: "RecordFeedback",
			Handler:    _HivemindService_RecordFeedback_Handler,
		},
		{
			MethodName: "GetStats",
			Handler:    _HivemindService_GetStats_Handler,
		},
		{
			MethodName: "TriggerConsolidation",
			Handler:    _HivemindService_TriggerConsolidation_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _HivemindService_HealthCheck_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}
